version: '3.8'

services:
  # API-сервис с OpenAI API
  doc-analysis-api:
    build:
      context: .
      dockerfile: ./api-service/Dockerfile
    container_name: doc_analysis_api
    restart: unless-stopped
    ports:
      - "8002:8000"
    environment:
      # Proxy настройки (опционально, раскомментируйте если нужен прокси)
      # - HTTPS_PROXY=${HTTPS_PROXY:-}
      # - HTTP_PROXY=${HTTP_PROXY:-}
      # Исключения для внутренних IP (не ходят через прокси)
      - NO_PROXY=localhost,127.0.0.1,doc-analysis-ui-react,doc-analysis-api
      - PYTHONUNBUFFERED=1
    volumes:
      # Монтируем .env с API ключами (read-only для безопасности)
      - ./api-service/.env:/app/.env:ro
    networks:
      - doc-analysis-net
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/')"]
      interval: 30s
      timeout: 10s
      retries: 3
  doc-analysis-ui-react:
    build: ./ui-react-service
    container_name: doc_analysis_ui_react
    restart: unless-stopped
    ports:
      - "7862:80"
    environment:
      - API_SERVICE_URL=http://doc-analysis-api:8000
    networks:
      - doc-analysis-net
    depends_on:
      - doc-analysis-api

networks:
  doc-analysis-net:
    driver: bridge
